---
- name: Deploy Flask Blog App
  hosts: flask_servers
  become: yes
  vars:
    flask_app_dir: "/opt/flask_blog_app"
    flask_env: "production"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - libpq-dev
          - nginx
          - git
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv
        executable: pip3

    - name: Create Flask app directory
      file:
        path: "{{ flask_app_dir }}"
        state: directory

    - name: Clone Flask app repository
      git:
        repo: 'https://your_git_repo_url'
        dest: "{{ flask_app_dir }}"
        version: master  # Or any branch you want to deploy
        force: yes

    - name: Set up virtual environment
      command: virtualenv venv
      args:
        chdir: "{{ flask_app_dir }}"

    - name: Install required Python dependencies
      pip:
        requirements: "{{ flask_app_dir }}/requirements.txt"
        virtualenv: "{{ flask_app_dir }}/venv"

    - name: Create database (if not exists)
      command: python3 app.py create_db
      args:
        chdir: "{{ flask_app_dir }}"

    - name: Set up Gunicorn systemd service
      template:
        src: gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service

    - name: Start Gunicorn
      systemd:
        name: gunicorn
        state: started
        enabled: yes

    - name: Configure Nginx
      template:
        src: nginx_flask_app.conf.j2
        dest: /etc/nginx/sites-available/flask_blog_app
      notify:
        - Restart Nginx

    - name: Enable Nginx site
      command: "ln -s /etc/nginx/sites-available/flask_blog_app /etc/nginx/sites-enabled/"
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
