#- hosts: localhost
#  tasks:
#  - debug:
#      msg: "testing github action workflow v1"

- name: Ensure nginx is installed and running
  hosts: localhost  # Change to the group of hosts you want to target
  become: yes  # Use 'sudo' to gain root privileges
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure nginx is started
      service:
        name: nginx
        state: started
        enabled: yes
