---
- name: Setup Flask Web Server
  hosts: webservers
  become: yes  # Use sudo privileges

  vars:
    python_version: "3.8"  # Version of Python to use
    app_directory: "/home/ubuntu/flask_app"  # Directory for Flask app

  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Add deadsnakes PPA for Python 3.8
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Install Python 3.8 and required packages
      apt:
        name:
          - python3.8
          - python3.8-dev
          - python3-pip
          - python3-venv
        state: present

    - name: Create virtual environment for Flask app
      command: python{{ python_version }} -m venv {{ app_directory }}/venv
      args:
        creates: "{{ app_directory }}/venv/bin/activate"  # Check if the virtual environment already exists

    - name: Install Flask in virtual environment
      pip:
        name: flask
        virtualenv: "{{ app_directory }}/venv"

    - name: Create Flask app script
      copy:
        dest: "{{ app_directory }}/app.py"
        content: |
          from flask import Flask
          app = Flask(__name__)

          @app.route('/')
          def hello_world():
              return 'Hello, World!'

          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=5000)

    - name: Start Flask app
      command: "{{ app_directory }}/venv/bin/python {{ app_directory }}/app.py"
      async: 300  # Run asynchronously (timeout after 5 minutes)
      poll: 0     # Don't wait for it to finish immediately
