name: CI for Flask Web Server Playbook

on:
  push:
    branches:
      - main  # Triggers the workflow when changes are pushed to the main branch

jobs:
  setup:
    name: Setup CI for Flask Web Server
    runs-on: ubuntu-24.04-arm  # Specify the runner OS

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Set up Python (if needed for the playbook execution)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies (Flask, etc.)
      - name: Install Flask and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask

      # Create the Ansible inventory file dynamically
      - name: Create inventory file
        run: |
          echo -e "[webservers]\nlocalhost ansible_connection=local" > inventory.ini

      # Run the Ansible playbook to set up the Flask server
      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory.ini playbooks/setup-flask.yml

      # Test if the Flask app is running (optional)
      - name: Test Flask web server
        run: |
          curl http://localhost:5000  # Assuming the Flask app runs on port 5000
