name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Release
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{steps.update-version.outputs.version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: ${{steps.update-version.outputs.version}}
          tag_name: ${{steps.update-version.outputs.version}}
          target_commitish: ${{ steps.tag.outputs.sha }}
